from pyshacl import Validator
from rdflib import Graph



mydata = """
@prefix : <http://www.semanticweb.org/smhhborg/ontologies/2024/4/untitled-ontology-140/> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix xml: <http://www.w3.org/XML/1998/namespace> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix ontologies: <https://nfdi4cat.org/ontologies/> .
@base <http://www.semanticweb.org/smhhborg/ontologies/2024/4/untitled-ontology-140/> .

<http://www.semanticweb.org/smhhborg/ontologies/2024/4/untitled-ontology-140> rdf:type owl:Ontology .

#################################################################
#    Object Properties
#################################################################

###  https://nfdi4cat.org/ontologies/reac4cat_000081
ontologies:reac4cat_000081 rdf:type owl:ObjectProperty ;
                           rdfs:label "ra_1"@de .


###  https://nfdi4cat.org/ontologies/reac4cat_000082
ontologies:reac4cat_000082 rdf:type owl:ObjectProperty ;
                           rdfs:subPropertyOf owl:topObjectProperty ;
                           rdfs:label "ra_2"@de .


###  https://nfdi4cat.org/ontologies/reac4cat_000083
ontologies:reac4cat_000083 rdf:type owl:ObjectProperty ;
                           rdfs:subPropertyOf owl:topObjectProperty ;
                           rdfs:label "ra_3"@de .


#################################################################
#    Classes
#################################################################

###  https://nfdi4cat.org/ontologies/reac4cat_000077
ontologies:reac4cat_000077 rdf:type owl:Class ;
                           rdfs:label "A_1"@de .


###  https://nfdi4cat.org/ontologies/reac4cat_000078
ontologies:reac4cat_000078 rdf:type owl:Class ;
                           rdfs:label "A_2"@de .


###  https://nfdi4cat.org/ontologies/reac4cat_000079
ontologies:reac4cat_000079 rdf:type owl:Class ;
                           rdfs:label "A_3"@de .


###  https://nfdi4cat.org/ontologies/reac4cat_000080
ontologies:reac4cat_000080 rdf:type owl:Class ;
                           rdfs:label "A_4"@de .


#################################################################
#    Individuals
#################################################################

###  https://nfdi4cat.org/ontologies/reac4cat_000084
ontologies:reac4cat_000084 rdf:type owl:NamedIndividual ,
                                    ontologies:reac4cat_000077 ;
                           ontologies:reac4cat_000081 ontologies:reac4cat_000085 ;
                           rdfs:label "a_1"@de .


###  https://nfdi4cat.org/ontologies/reac4cat_000085
ontologies:reac4cat_000085 rdf:type owl:NamedIndividual ,
                                    ontologies:reac4cat_000078 ;
                           ontologies:reac4cat_000082 ontologies:reac4cat_000086 ;
                           ontologies:reac4cat_000083 ontologies:reac4cat_000088 ;
                           rdfs:label "a_2"@de .


###  https://nfdi4cat.org/ontologies/reac4cat_000086
ontologies:reac4cat_000086 rdf:type owl:NamedIndividual ,
                                    ontologies:reac4cat_000079 ;
                           rdfs:label "a_3"@de .


###  https://nfdi4cat.org/ontologies/reac4cat_000088
ontologies:reac4cat_000088 rdf:type owl:NamedIndividual ,
                                    ontologies:reac4cat_000080 ;
                           rdfs:label "a_4"@de .


###  Generated by the OWL API (version 4.5.26.2023-07-17T20:34:13Z) https://github.com/owlcs/owlapi

"""
g = Graph()
g.parse(data=mydata, format="ttl")
shapes = """
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix sh:    <http://www.w3.org/ns/shacl#> .
@prefix xsd:   <http://www.w3.org/2001/XMLSchema#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix ex:    <https://nfdi4cat.org/ontologies/reac4cat_> .


ex:PersonShape
    a sh:NodeShape ;
    sh:targetClass ex:000077 ;
	sh:property [
        sh:path ex:000081 ;
        sh:class ex:000078 ;
        sh:minCount 1 ;
    ] ;
	sh:rule [
	a 	sh:SPARQLRule ;
        sh:prefixes [
			sh:declare [
				sh:namespace "https://nfdi4cat.org/ontologies/reac4cat_";
				sh:prefix "ex";];
				];
        sh:construct \"""
            CONSTRUCT {?a ex:000086 ?b.}
            WHERE {
                ?a a ex:000077 .
                ?a ex:000081 ?b .
                ?b a ex:000078 .
            }
        \""" ;
		
    ]
    .
"""

myshapes = Graph()
myshapes.parse(data=shapes, format="turtle")

v = Validator(g, shacl_graph=myshapes, options={"advanced": True, "inference": "rdfs"})
conforms, report_graph, report_text = v.run()
expanded_graph = v.target_graph #<-- This gets the expanded data graph
# export graph as ttl-file
expanded_graph.serialize(destination='C:/Users/smhhborg/Documents/GitHub/Test_for_advanced_SHACL_features/expanded_graph.ttl', format='turtle')